### ISSUE TITLE
3. Main section

### ISSUE THREAD

**Issue by PNKBizz** [FankaPanik/homeworksf#4]
1. https://github.com/FankaPanik/homeworksf/blob/cd68b49fb163ff4c01b23c56412dfa54f6fd6a60/index.html#L120-L128
Вот тут должны быть ссылки. Пока пустые.

2. https://github.com/FankaPanik/homeworksf/blob/cd68b49fb163ff4c01b23c56412dfa54f6fd6a60/index.html#L172-L178
Прекрасно!

3. https://github.com/FankaPanik/homeworksf/blob/cd68b49fb163ff4c01b23c56412dfa54f6fd6a60/index.html#L179
Лучше `button`

4. https://github.com/FankaPanik/homeworksf/blob/cd68b49fb163ff4c01b23c56412dfa54f6fd6a60/index.html#L330-L332
Наоборот `li -> a`

5. https://github.com/FankaPanik/homeworksf/blob/cd68b49fb163ff4c01b23c56412dfa54f6fd6a60/index.html#L491-L496
Давай сделаем 
```
a.sell[href="#"]
  div.sell-num
  ...
```
И для класса `.sell` пропиши явно `display: block`

**Comment by FankaPanik** [comment]
5 непонятно, эти цифры в кружочках должны быть ссылками?

**Comment by PNKBizz** [comment]
![image](https://user-images.githubusercontent.com/17909924/68923433-5d953a00-078f-11ea-954e-85c3b6ea771b.png)

Почему в кружочках? Это вот эта часть. Это будут ссылки на другие разделы этого блока. Потом прикрутим интерактив с помощью JS

**Comment by PNKBizz** [comment]
![image](https://user-images.githubusercontent.com/17909924/68924389-c978a200-0791-11ea-8017-3e161eee0fb3.png)
Вот эти элементы у тебя сейчас сделаны через абсолютное позиционирование. Давай тоже от него уйдем в пользу нормального потока. Вообще нужно стараться сохранять поток документа. Это очень сильно упрощает верстку и уберегает от дальнейших ошибок )
Я бы сделал эти блоки через враппер с `background-image` и паддингами. Он сам будет распирать пространство и можно будет убрать огромный маржин в 400px )

**Comment by PNKBizz** [comment]
![image](https://user-images.githubusercontent.com/17909924/68925496-3b51eb00-0794-11ea-9333-61fa3dcf7e2a.png)
см. выше
